// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'table-td': string;
  'tableTd': string;
}
declare var cssExports: CssExports;
export = cssExports;
